FROM ubuntu:bionic
MAINTAINER Alan Franzoni <username@franzoni.eu>
ENV DEBIAN_FRONTEND=noninteractive
COPY 80-acquire-retries /etc/apt/apt.conf.d/
RUN apt-get update && apt-get -y install apt-transport-https curl gnupg ruby rubygems-integration ruby-dev build-essential rsync
RUN apt-get -y dist-upgrade
RUN gem install fpm -v 1.9.3
