FROM fwd-fedora-26:latest
MAINTAINER Alan Franzoni <username@franzoni.eu>
# whatever is required for building should be installed in this image; just like BuildRequires: for RPM specs
RUN dnf -y install readline-devel
