FROM fwd-centos-5-i386:latest
MAINTAINER Alan Franzoni <username@franzoni.eu>
# whatever is required for building should be installed in this image; just like BuildRequires: for RPM specs
RUN linux32 yum -y install readline-devel libtermcap
