name: ci
run-name: test
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro-and-version: ["fwd-rockylinux-9", "fwd-ubuntu-noble", "fwd-ubuntu-jammy", "fwd-ubuntu-focal", "fwd-debian-bullseye", "fwd-debian-bookworm"]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build 
        run: cd ${{ matrix.distro-and-version }} && ./build
      - name: test
        run: cd ${{ matrix.distro-and-version }} && ./test/test
