name: ci
run-name: test
on: 
  push:
    branches:
      - main

jobs:
  arm-build:
    runs-on: ubuntu-latest
    concurrency:
      group: build-and-test
      cancel-in-progress: true  
    strategy:
      matrix:
        distro-and-version: ["fedora-40"]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: alanfranz
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and export to docker
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          context: fwd-${{matrix.distro-and-version}}
          load: true
          tags: fwd-${{matrix.distro-and-version}}
      - name: test
        run: cd fwd-${{matrix.distro-and-version}} && ./test/test
          

  build-and-test:
    if: false
    runs-on: ubuntu-latest
    concurrency:
      group: build-and-test
      cancel-in-progress: true  
    strategy:
      matrix:
        distro-and-version: ["fedora-40", "rockylinux-8", "rockylinux-9", "ubuntu-noble", "ubuntu-jammy", "ubuntu-focal", "debian-bullseye", "debian-bookworm"]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build 
        run: cd fwd-${{ matrix.distro-and-version }} && ./build
      - name: test
        run: cd fwd-${{ matrix.distro-and-version }} && ./test/test
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: alanfranz
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: push Docker image
        id: push
        run: |
          docker tag fwd-${{ matrix.distro-and-version }} docker.io/alanfranz/fpm-within-docker:${{ matrix.distro-and-version }}
          docker push docker.io/alanfranz/fpm-within-docker:${{ matrix.distro-and-version }} 
