name: ci
run-name: test
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro-and-version: ["fwd-fedora-40", "fwd-rockylinux-9", "fwd-ubuntu-noble", "fwd-ubuntu-jammy", "fwd-ubuntu-focal", "fwd-debian-bullseye", "fwd-debian-bookworm"]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build 
        run: cd ${{ matrix.distro-and-version }} && ./build
      - name: test
        run: cd ${{ matrix.distro-and-version }} && ./test/test
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: alanfranz
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: push Docker image
        id: push
        run: |
          docker tag ${{ matrix.distro-and-version }} docker.io/alanfranz/fpm-within-docker:${{ matrix.distro-and-version }}
          docker push docker.io/alanfranz/fpm-within-docker:${{ matrix.distro-and-version }} 
